version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  run-test-suite:
    docker:
      - image: circleci/node:14.15.4
    working_directory: ~/project
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Fetch dependencies
          command: yarn install --no-progress --non-interactive --silent --pure-lockfile
      - run:
          name: Run test suite
          command: yarn test_ci
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy-to-netlify:
    docker:
      - image: circleci/node:14.15.4
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: curl -X POST -d {} ${HOOK}
      - codecov/upload:
          file: './coverage/clover.xml'
          token: ${CODECOV_TOKEN}
workflows:
  test-and-deploy:
    jobs:
      - run-test-suite
      - deploy-to-netlify:
          requires:
            - run-test-suite
          filters:
            branches:
              only: main
